// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loader': string;
  'loader-animation': string;
  'loaderAnimation': string;
  'loaderContainer': string;
  'loaderContainerContent': string;
  'loader__container': string;
  'loader__container__content': string;
}
export const cssExports: CssExports;
export default cssExports;
