// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'info-card': string;
  'info-card__content': string;
  'info-card__content__body': string;
  'info-card__subtext': string;
  'info-card__subtext__label': string;
  'info-card__subtext__value': string;
  'info-card__title': string;
  'infoCard': string;
  'infoCardContent': string;
  'infoCardContentBody': string;
  'infoCardSubtext': string;
  'infoCardSubtextLabel': string;
  'infoCardSubtextValue': string;
  'infoCardTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
